### ISSUE TITLE
remove_residues_by_index can have some strange outcomes when indexes are not in sequence, should it check residue.index?

### ISSUE THREAD

**Issue by LouieSlocombe** [mwinokan/MolParse#11]
def remove_residues_by_number(self, del_list: list, fix_indices=True):
    import mcol
    import mout

    if fix_indices:
      self.fix_indices()
    for chain in self.chains:
      for index, residue in reversed(list(enumerate(chain.residues))):
        if residue.index in del_list:
          del chain.residues[index]
    return None

**Comment by mwinokan** [comment]
Do you mean indexes of the residues in the system or the del_list is out of order?

**Comment by mwinokan** [comment]
I refactored `System.remove_residues_by_number` into `System.remove_residues`. Please can you check if you still see the same behaviour, and if so can you please make a test that catches it in `tests/sys_delete.py`

**Comment by LouieSlocombe** [comment]
Ok will check when I can

**Comment by LouieSlocombe** [comment]
Seems to have done the job, sorry I am super short on time not sure if I can write a test for it today

**Comment by mwinokan** [comment]
No worries at all. If it works it doesn't need a test #famouslastwords

**Comment by LouieSlocombe** [comment]
I would push your fix to PyPI as it is fairly important

**Comment by mwinokan** [comment]
Pushed 0.0.13 to PyPI
