### ISSUE TITLE
If the residue is non-standard it can crash the pdb loader, is there a better way to deal with it?

### ISSUE THREAD

**Issue by LouieSlocombe** [mwinokan/MolParse#12]
Currently, to fix it, one could add the non-standard residue to residue.py under res_type(...) or the RES_TYPES dict.

Could default to protein?

**Comment by mwinokan** [comment]
Yes I've been aware of this issue, let me have a quick look.

My first instinct would be to make unknown things a ligand as protein residues have standard naming (except chromophores)

**Comment by LouieSlocombe** [comment]
Can I add more chromophores under the PRO?

**Comment by mwinokan** [comment]
Sure, just do that in your local copy for now. I am working on a better fix

**Comment by mwinokan** [comment]
@LouieSlocombe please see new functionality to override hard-coded residue typing:

```
from molparse.residue import add_res_type
add_res_type('CROW','LIP')
```

Please verify this works for you. I'll merge your extra chromophores too

**Comment by LouieSlocombe** [comment]
Sorry for the delay, this works as expected

**Comment by mwinokan** [comment]
Thanks @LouieSlocombe
